import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import { ReservationProvider } from "./_components/ReservationContext";
import { UserProvider } from "./_components/UserContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReservationProvider>
        <UserProvider>
          
          
        <section className="flex flex-col h-screen !min-h-screen">
    {/* <header className="flex justify-between items-center bg-gray-900 min-h-14  text-white px-2 lg:px-7 border-b-2 border-gray-800">
      <Link href={"/"} className="capitalize">Best restaurant</Link>
      <div className="flex gap-1 text-xs sm:text-sm sm:gap-5">
        <Link href={"/tables"} className="capitalize">Tables</Link>
        <Link href={"/bookings"} className="capitalize">My Bookings</Link>
      <Username></Username>
      </div>
    </header> */}
    <Header></Header>
    
    {/* <main className="flex-1 overflow-y-scroll"> */}
    <main className="flex flex-1">
      {children}
    </main>
    
   </section>
        </UserProvider>
        </ReservationProvider>
      </body>
    </html>
  );
}
